# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: "http://wyong.cn"
date_format: "ordinal"
title: 威廉
subtitle: "淡泊明志"
description: "王勇的个人博客"
keywords: 威廉, 王勇, wvalianty, 博客
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Yong Wang
organization: 
organization_url: 
github_username: wvalianty
location: Beijing, China
email: 18513169404@163.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: wvalianty/wvalianty.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: wvalianty
    repo: blog-comments
    oauth:
        client_id: cc7e072f0b08cd650887 
        client_secret: 46c9a3ba83bd648a56dfe2f363f907ae9c71c48b 
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: wvalianty
    repo: blog-comments
    clientID: cc7e072f0b08cd650887
    clientSecret: 46c9a3ba83bd648a56dfe2f363f907ae9c71c48b
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
#google:
#    analytics_id: UA-80669434-1
